# Generated by Django 6.1.1 on 2026-09-19 10:51

import uuid
from typing import Any

import django.db.models.deletion
from django.db import migrations, models


def seed_initial_dataset(apps: Any, schema_editor: Any) -> None:
    PricingDataset = apps.get_model("stations", "PricingDataset")
    Station = apps.get_model("stations", "Station")
    StationPrice = apps.get_model("stations", "StationPrice")

    if Station.objects.exists():
        prices = list(Station.objects.values_list("retail_price", flat=True))
        min_p = min(prices) if prices else None
        max_p = max(prices) if prices else None
        dataset = PricingDataset.objects.create(
            version_code="OPIS-INITIAL",
            filename="fuel-prices-for-be-assessment.csv",
            file_hash="c704371f141ded9c54df6c32d488a0ba2ceb589f88c936c967daa5330e0cd241",
            station_count=len(prices),
            min_price=min_p,
            max_price=max_p,
            is_active=True,
            description="Baseline OPIS fuel pricing dataset for US truck stops.",
        )
        station_prices = [
            StationPrice(
                dataset=dataset,
                station_id=st_id,
                retail_price=price,
            )
            for st_id, price in Station.objects.values_list("id", "retail_price")
        ]
        StationPrice.objects.bulk_create(station_prices, batch_size=1000)


def reverse_seed(apps: Any, schema_editor: Any) -> None:
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingDataset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version_code",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_hash", models.CharField(db_index=True, max_length=64)),
                ("station_count", models.PositiveIntegerField(default=0)),
                (
                    "min_price",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "max_price",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StationPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("retail_price", models.DecimalField(decimal_places=3, max_digits=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="station_prices",
                        to="stations.pricingdataset",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="stations.station",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["dataset", "station"],
                        name="stations_st_dataset_4909d4_idx",
                    )
                ],
                "unique_together": {("dataset", "station")},
            },
        ),
        migrations.RunPython(seed_initial_dataset, reverse_seed),
    ]
